services:
  bundle-server:
    url: http://localhost:8000
bundles:
  tenantA:
    service: bundle-server
    resource: /bundles/tenantA/bundle.tar.gz
  tenantB:
    service: bundle-server
    resource: /bundles/tenantB/bundleB.tar.gz